### ISSUE TITLE
female first names

### ISSUE THREAD

**Issue by lifeparticle** [lifeparticle/Bangla-Name-Generator#3]

**Comment by manasivaraiya** [comment]
What is exactly needed?

**Comment by lifeparticle** [comment]
here is the data source

https://github.com/faruk-ahmad/bengali-female-vs-male-names/blob/master/db/female.txt

we need to clean the data so that we only have the first name in female.txt and it should go under api/data/

**Comment by manasivaraiya** [comment]
there's small issue here. I'm not familiar with the language used in the given link! Moreover i don't even know how is that done.

**Comment by lifeparticle** [comment]
It's [Bengali language](https://en.wikipedia.org/wiki/Bengali_language), I had a quick look, I think there are some data with last names in that file
```
first_name space last_name
```

For example Line 68 in https://github.com/faruk-ahmad/bengali-female-vs-male-names/blob/master/db/female.txt

```
ফাবিহা বুশরা
```
we just need to clean those data so that we have only first names in female_first_names.txt

**Comment by manasivaraiya** [comment]
so i basically need to delete all the other words except for the first word? right? I am not familiar with bengali language. so i won't be able to distinguish between a male/female word.

**Comment by lifeparticle** [comment]
Yes, that's correct. In the following file, you only have female names, so no need to worry.

https://github.com/faruk-ahmad/bengali-female-vs-male-names/blob/master/db/female.txt

**Comment by manasivaraiya** [comment]
ohh got it. thanks
