### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by lifeparticle** [lifeparticle/Bangla-Name-Generator#5]

**Comment by manasivaraiya** [comment]
Can i contribute??

**Comment by lifeparticle** [comment]
Sure, thank you for your interest! I think for this we need a separate repo. I was thinking to use https://www.netlify.com/. But first we need to develop the serverless function.

**Comment by manasivaraiya** [comment]
yes. a separate repo has to be created on github itself. but can you explain me what exactly has to be made in the front end part?

**Comment by lifeparticle** [comment]
Yeah, so maybe a generate button with two radio buttons o Male o Female. The generate button will call the serveless function and show the result depend on the input given by the user.

**Comment by manasivaraiya** [comment]
okay, cool. I can try doing that but have you created a repo??

**Comment by lifeparticle** [comment]
https://github.com/lifeparticle/Bangla-Name-Generator-Frontend

Thank you!

**Comment by manasivaraiya** [comment]
I tried doing it but I'm struggling a bit during the display part. Does this small task given by you contain back-end? if yes. I'm not familiar with back-end.  I can work on the front-end and the designing part.

**Comment by lifeparticle** [comment]
Yes, it does. That's not a problem, you can still design the frontend without the logic part. Thanks for your kind help!

**Comment by manasivaraiya** [comment]
Just let me know what kind of css or bootstrap stylings do you need. I'd be glad to help.

**Comment by lifeparticle** [comment]
Can you please use the latest https://getbootstrap.com/ . Thanks

**Comment by manasivaraiya** [comment]
Yes sure. But can you give me a basic idea of what all should be present on that page. So that I can implement it.

**Comment by lifeparticle** [comment]
Something like this.
![Desktop HD](https://user-images.githubusercontent.com/1612112/94987371-55add680-05a9-11eb-845d-0c0e626262a1.png)
